GH-485: adding advanced configurable parameters
MASQ-Project/Node pull request #115
Opened 2022-03-17 18:27 UTC by bertllll

I had to recreate this PR because did not update automatically for some reason.

2022-03-17 21:38 UTC, FinsaasGH approved these changes

2022-03-18 03:01 UTC, kauri-hero requested changes
@bertllll 
I have updated the recommended defaults

2022-03-18 03:01 UTC, kauri-hero commented on node/src/sub_lib/neighborhood.rs
> +    exit_service_rate: 300,
After further review, I believe we should have the defaults as follows:

    routing_byte_rate: 1,
    routing_service_rate: 10,
    exit_byte_rate: 2,
    exit_service_rate: 20

2022-03-18 03:01 UTC, kauri-hero commented on node/src/sub_lib/accountant.rs
> +        threshold_interval_sec: 2_592_000,
I misunderstood the variable earlier in my notes, so this needs to be corrected to:

threshold_interval_sec: 1800

2022-03-18 03:01 UTC, kauri-hero commented on node/src/sub_lib/accountant.rs
> +        debt_threshold_gwei: 10_000_000_000,
I made an error here for this value - it should be 1 MASQ:

debt_threshold_gwei: 1_000_000_000

2022-03-18 03:01 UTC, kauri-hero commented on node/src/sub_lib/accountant.rs
> +        };
if these defaults also need to be changed, please have them match the default corrections I made above

2022-03-18 08:50 UTC, bertllll commented on node/src/sub_lib/accountant.rs
> +        threshold_interval_sec: 2_592_000,
I feel I will need to discuss this one further with you.

2022-03-18 09:35 UTC, bertllll commented on node/src/sub_lib/accountant.rs
> +        threshold_interval_sec: 2_592_000,
We ended up with 21600 being better.

2022-03-18 12:08 UTC, FinsaasGH approved these changes

2022-03-18 12:09 UTC, FinsaasGH approved these changes

2022-03-18 13:20 UTC, FinsaasGH approved these changes

2022-03-18 19:27 UTC, kauri-hero approved these changes

2022-03-18 19:42 UTC, merged