GH-781: New Testnet Polygon Amoy
MASQ-Project/Node pull request #431
Opened 2024-04-02 08:30 UTC by bertllll

2024-04-02 10:48 UTC, bertllll commented on node/Cargo.toml
> +http = "0.1.21"
Hmm. I should revert this.

2024-04-02 12:37 UTC, utkarshg6 requested changes

2024-04-02 12:37 UTC, utkarshg6 commented on masq_lib/src/test_utils/utils.rs
> +    is_env_variable_set("ALLOW_TEST_DATA_ESCAPE_PROJECT_DIR", "true")
Let's pour some more ideas if we can find a way around this.

2024-04-02 12:37 UTC, utkarshg6 commented on node/Cargo.toml
> +http = "0.1.21"
Yeah you should.

2024-04-02 12:37 UTC, utkarshg6 commented on node/src/daemon/setup_reporter.rs
>      fn get_modified_setup_tilde_in_config_file_path() {
I'm glad that you discovered this. Just my personal opinion, I'd be afraid of an application creating files in my computer outside the project directory.

A possible solution: Maybe use container provided by Docker.

2024-04-03 09:26 UTC, utkarshg6 approved these changes

2024-04-03 09:26 UTC, utkarshg6 commented on node/src/node_configurator/node_configurator_standard.rs
> +        let node_home_dir = ensure_node_home_directory_exists(
I'd prefer `home_dir`. Also, let's change the function name to also say, `ensure_home_directory_exists`.

2024-04-03 09:26 UTC, utkarshg6 commented on node/src/test_utils/mod.rs
> +pub fn make_node_base_dir_and_return_its_absolute_and_relative_path_to_os_home_dir(
You mentioned that "why it still exists?". I think you'd like to remove it and change the code inside tests if it's used there. Good Luck :+1:

2024-04-03 14:08 UTC, merged